const DCE_CONFIG = Object.freeze({
  APP_NAME: 'AGF Eleicoes',
  VERSION: '0.4.0',
  MAX_IMPORT_CHUNK: 200,
  MAX_ADDRESS_CHUNK: 200,
  MAX_PORTAL_RETURN_CHUNK: 200,
  MAX_RESULT_CHUNK: 20,
  VOLUME_CAPACITY: 250,
  PROPERTY_SPREADSHEET_ID: 'DCE_SPREADSHEET_ID',
  PROPERTY_ROOT_FOLDER_ID: 'DCE_ROOT_FOLDER_ID',
  PROPERTY_API_TOKEN: 'DCE_API_TOKEN',
  SHEETS: Object.freeze({
    USERS: ['ID', 'EMAIL', 'STATUS', 'CREATED_AT', 'UPDATED_AT'],
    COMPANIES: ['ID', 'USER_ID', 'CNPJ', 'NAME', 'SERIES', 'NEXT_NUMBER', 'PROFILE_JSON', 'CREATED_AT', 'UPDATED_AT'],
    IMPORTS: ['ID', 'USER_ID', 'FILE_NAME', 'FILE_TYPE', 'STATUS', 'TOTAL_ROWS', 'VALID_ROWS', 'ERROR_ROWS', 'CREATED_AT', 'UPDATED_AT'],
    REMITTANCES: ['ID', 'USER_ID', 'IMPORT_ID', 'TRACKING_CODE', 'SERVICE', 'REFERENCE', 'STATUS', 'DOCUMENT_JSON', 'ERRORS_JSON', 'CREATED_AT', 'UPDATED_AT'],
    BATCHES: ['ID', 'USER_ID', 'COMPANY_ID', 'ENVIRONMENT', 'STATUS', 'TOTAL', 'AUTHORIZED', 'REJECTED', 'ERRORS', 'CREATED_AT', 'UPDATED_AT'],
    DCE: ['ID', 'USER_ID', 'BATCH_ID', 'REMITTANCE_ID', 'CNPJ', 'SERIES', 'NUMBER', 'NUMERIC_CODE', 'ACCESS_KEY', 'STATUS', 'CSTAT', 'REASON', 'PROTOCOL', 'AUTHORIZED_AT', 'SIGNED_XML_FILE_ID', 'PROCESSED_XML_FILE_ID', 'DACE_FILE_ID', 'CREATED_AT', 'UPDATED_AT'],
    EVENTS: ['ID', 'USER_ID', 'DCE_ID', 'TYPE', 'STATUS', 'PROTOCOL', 'DETAILS_JSON', 'CREATED_AT'],
    CAMPAIGNS: ['ID', 'NAME', 'CNPJ', 'CANDIDATE_NAME', 'OFFICE', 'STATUS', 'PROFILE_JSON', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT'],
    CAMPAIGN_USERS: ['ID', 'CAMPAIGN_ID', 'USER_ID', 'ROLE', 'STATUS', 'CREATED_AT', 'UPDATED_AT'],
    ADDRESS_LISTS: ['ID', 'CAMPAIGN_ID', 'FILE_NAME', 'STATUS', 'TOTAL_ROWS', 'READY_ROWS', 'REVIEW_ROWS', 'REJECTED_ROWS', 'SOURCE_METADATA_JSON', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT'],
    ADDRESS_ROWS: ['ID', 'CAMPAIGN_ID', 'ADDRESS_LIST_ID', 'ROW_NUMBER', 'STATUS', 'ORIGINAL_JSON', 'CLEANED_JSON', 'ISSUES_JSON', 'CLEANING_BATCH_ID', 'PORTAL_EXPORT_ID', 'CREATED_AT', 'UPDATED_AT'],
    CLEANING_BATCHES: ['ID', 'CAMPAIGN_ID', 'ADDRESS_LIST_ID', 'STATUS', 'PROCESSED', 'READY', 'REVIEW', 'REJECTED', 'SUMMARY_JSON', 'CREATED_BY', 'CREATED_AT'],
    PORTAL_EXPORTS: ['ID', 'CAMPAIGN_ID', 'ADDRESS_LIST_ID', 'SERVICE', 'STATUS', 'TOTAL_ROWS', 'FILE_NAME', 'FILE_ID', 'SHA256', 'CREATED_BY', 'CREATED_AT'],
    PORTAL_RETURNS: ['ID', 'CAMPAIGN_ID', 'PORTAL_EXPORT_ID', 'STATUS', 'TOTAL_ROWS', 'PAC_ROWS', 'SEDEX_ROWS', 'INVALID_ROWS', 'MATRIX_SUMMARY_JSON', 'CSV_FILE_NAME', 'CSV_SHA256', 'PDF_FILES_JSON', 'DOCUMENT_MODE', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT'],
    POSTAL_OBJECTS: ['ID', 'CAMPAIGN_ID', 'PORTAL_RETURN_ID', 'TRACKING_CODE', 'SERVICE', 'STATUS', 'POSTAL_JSON', 'RECIPIENT_JSON', 'CONTENT', 'REFERENCE', 'ACCESS_KEY', 'PROTOCOL', 'ERRORS_JSON', 'MATRIX_STATUS', 'MATRIX_JSON', 'PRODUCTION_BATCH_ID', 'VOLUME_ID', 'CREATED_AT', 'UPDATED_AT'],
    PRODUCTION_BATCHES: ['ID', 'CAMPAIGN_ID', 'PORTAL_RETURN_ID', 'DOCUMENT_MODE', 'STATUS', 'TOTAL', 'PAC', 'SEDEX', 'MATRIX_SUMMARY_JSON', 'CREATED_BY', 'CREATED_AT', 'UPDATED_AT'],
    DELIVERY_VOLUMES: ['ID', 'CAMPAIGN_ID', 'PRODUCTION_BATCH_ID', 'SERVICE', 'VOLUME_NUMBER', 'TOTAL_VOLUMES', 'QUANTITY', 'TRACKING_CODES_JSON', 'STATUS', 'DELIVERED_AT', 'RECEIVED_BY', 'PROOF_FILE_ID', 'CREATED_AT', 'UPDATED_AT'],
    OPERATION_EVENTS: ['ID', 'CAMPAIGN_ID', 'USER_ID', 'TYPE', 'SOURCE_TYPE', 'SOURCE_ID', 'SERVICE', 'QUANTITY', 'IDEMPOTENCY_KEY', 'METADATA_JSON', 'OCCURRED_AT', 'CREATED_AT'],
    DAILY_SUMMARIES: ['ID', 'CAMPAIGN_ID', 'DATE', 'METRICS_JSON', 'UPDATED_AT'],
    LOGS: ['ID', 'USER_ID', 'ACTION', 'LEVEL', 'MESSAGE', 'DETAILS_JSON', 'CREATED_AT']
  })
});

function getScriptProperties_() {
  return PropertiesService.getScriptProperties();
}

function getSpreadsheet_() {
  const id = getScriptProperties_().getProperty(DCE_CONFIG.PROPERTY_SPREADSHEET_ID);
  if (!id) throw new Error('Execute setupProject() antes de publicar o Web App.');
  return SpreadsheetApp.openById(id);
}

function getRootFolder_() {
  const id = getScriptProperties_().getProperty(DCE_CONFIG.PROPERTY_ROOT_FOLDER_ID);
  if (!id) throw new Error('Pasta raiz nao configurada. Execute setupProject().');
  return DriveApp.getFolderById(id);
}
