import "./client-portal.css";
import { getUser, logout } from "@netlify/identity";
import { api, dataAction, fileToBase64 } from "./api.js";
const root=document.querySelector("#client-portal"),toastBox=document.querySelector("#client-toast");
const S={user:null,campaigns:[],campaignId:"",view:"dashboard",ops:[],lots:[],company:null,cert:"",certName:"",pass:"",env:"2",from:"",to:""};
const NAV=[["dashboard","▥","Dashboard"],["simulator","▦","Simulador"],["authorization","✓","Autorizar DC-e"]];
const h=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const fmt=v=>new Intl.NumberFormat("pt-BR").format(Number(v||0));
function toast(m,t="info"){toastBox.textContent=m;toastBox.className=`client-toast show ${t}`;clearTimeout(toastBox._t);toastBox._t=setTimeout(()=>toastBox.className="client-toast",4200)}
function busy(label){const x=document.createElement("div");x.className="client-busy";x.innerHTML=`<div><span></span><strong>${h(label)}</strong></div>`;document.body.appendChild(x);return()=>x.remove()}
const campaign=()=>S.campaigns.find(x=>String(x.id)===String(S.campaignId));
const uname=()=>{const m=S.user?.user_metadata||{};return String(m.username||m.user_name||m.login||String(S.user?.email||"usuario").split("@")[0])};
function loginView(){root.innerHTML=`<main class="login-screen"><section class="login-card"><img src="/agf-logo.png" alt="AGF José Bonifácio e Correios"><h1>Acessar Portal</h1><form id="login"><label>Usuário<div><input name="username" autocomplete="username" required></div></label><label>Senha<div><input name="password" type="password" autocomplete="current-password" required></div></label><button>Entrar ›</button></form></section></main>`;root.querySelector("#login").onsubmit=async e=>{e.preventDefault();const stop=busy("Entrando...");try{const v=Object.fromEntries(new FormData(e.currentTarget)),r=await fetch("/api/portal/login",{method:"POST",credentials:"same-origin",headers:{"Content-Type":"application/json"},body:JSON.stringify(v)}),j=await r.json();if(!r.ok||!j.ok)throw new Error(j.error||"Usuário ou senha inválidos.");location.reload()}catch(err){toast(err.message,"error")}finally{stop()}}}
function shell(content){root.innerHTML=`<div class="client-app"><aside><img src="/agf-logo.png" alt="AGF José Bonifácio"><nav>${NAV.map(([id,i,l])=>`<button data-view="${id}" class="${S.view===id?"active":""}"><i>${i}</i>${l}</button>`).join("")}</nav></aside><main><header><strong>${NAV.find(x=>x[0]===S.view)?.[2]}</strong><div><span>${h(campaign()?.name||"Operação")}</span><button id="profile">${h(uname().slice(0,2).toUpperCase())}</button></div></header><section class="content">${content}</section></main><nav class="mobile-tabs">${NAV.map(([id,i,l])=>`<button data-view="${id}" class="${S.view===id?"active":""}"><i>${i}</i><small>${l}</small></button>`).join("")}</nav><div class="profile-menu"><button id="fiscal">Perfil fiscal</button><button id="signout">Sair</button></div><div class="modal"></div></div>`;root.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>{S.view=b.dataset.view;render()});root.querySelector("#profile").onclick=()=>root.querySelector(".profile-menu").classList.toggle("open");root.querySelector("#signout").onclick=async()=>{await logout();S.user=null;loginView()};root.querySelector("#fiscal").onclick=fiscalModal}
function filters(){return `<div class="filters"><label>Operação<select id="op">${S.campaigns.map(c=>`<option value="${h(c.id)}" ${String(c.id)===String(S.campaignId)?"selected":""}>${h(c.name||c.candidateName||c.cnpj)}</option>`).join("")}</select></label><label>De<input id="from" type="date" value="${h(S.from)}"></label><label>Até<input id="to" type="date" value="${h(S.to)}"></label><button id="apply">Aplicar</button></div>`}
function bindFilters(){root.querySelector("#apply")?.addEventListener("click",async()=>{S.campaignId=root.querySelector("#op").value;S.from=root.querySelector("#from").value;S.to=root.querySelector("#to").value;await loadData();render()})}
const filtered=()=>S.ops.filter(e=>(!S.from||String(e.occurredAt).slice(0,10)>=S.from)&&(!S.to||String(e.occurredAt).slice(0,10)<=S.to));
function qty(type,service){return filtered().filter(e=>e.type===type).reduce((a,e)=>{const d=String(e.service||"").toUpperCase(),m=e.metadata||{};if(!service)return a+Number(e.quantity||0);if(d===service)return a+Number(e.quantity||0);return a+(!d?Number(m[service.toLowerCase()]||0):0)},0)}
function values(service){const prepared=qty("LABEL_GENERATED",service),handed=qty("LABEL_HANDOFF",service),posted=qty("POSTING_COMPLETED",service),delivered=qty("TRACKING_DELIVERED",service);return{prepared,handed,posted,transit:Math.max(0,posted-delivered),delivered}}
const colors=["violet","blue","orange","navy","green"];
function service(name,v){const rows=[["Preparados",v.prepared],["Entregues à operação",v.handed],["Postados",v.posted],["Em trânsito",v.transit],["Entregues pelos Correios",v.delivered]],base=Math.max(1,v.prepared);return `<article class="card service"><h3>${name}</h3>${rows.map(([l,n],i)=>`<div class="metric"><span>${l}</span><div><i class="${colors[i]}" style="width:${Math.min(100,Math.round(n/base*100))}%"></i></div><b>${fmt(n)}</b><small>${v.prepared?Math.round(n/v.prepared*100):0}%</small></div>`).join("")}</article>`}
function dashboard(){if(!S.from){const d=S.ops.map(e=>String(e.occurredAt).slice(0,10)).filter(Boolean).sort(),today=new Date().toISOString().slice(0,10);S.from=d[0]||today;S.to=d.at(-1)||today}const p=values("PAC"),s=values("SEDEX"),t={prepared:p.prepared+s.prepared,handed:qty("LABEL_HANDOFF"),posted:qty("POSTING_COMPLETED"),delivered:qty("TRACKING_DELIVERED")};t.transit=Math.max(0,t.posted-t.delivered);const base=Math.max(1,t.prepared),del=Math.round(t.delivered/base*100),trans=Math.round(t.transit/base*100),events=filtered().slice().sort((a,b)=>String(b.occurredAt).localeCompare(String(a.occurredAt))).slice(0,8);shell(`<div class="hero"><h1>Acompanhamento da operação</h1><p>PAC, SEDEX e TOTAL com baixas parciais por período.</p></div>${filters()}<div class="services">${service("PAC",p)}${service("SEDEX",s)}${service("TOTAL",t)}</div><div class="lower"><article class="card"><h2>Linha do tempo</h2><div class="timeline">${events.map(e=>`<div><i></i><span><b>${h(String(e.type).replaceAll("_"," "))}</b><small>${h(new Date(e.occurredAt).toLocaleString("pt-BR"))}</small></span><strong>${fmt(e.quantity)}</strong></div>`).join("")||"Sem eventos no período."}</div></article><article class="card"><h2>Destaques</h2><div class="donut" style="--a:${del}deg;--b:${del+trans}deg"><span><b>${del}%</b><small>entregues</small></span></div><p><b>${fmt(t.posted)}</b> postados · <b>${fmt(t.transit)}</b> em trânsito · <b>${fmt(t.delivered)}</b> entregues</p></article></div>`);bindFilters()}
function simulator(){shell(`<div class="hero"><h1>Simulador</h1><p>Estimativa operacional.</p></div>${filters()}<div class="sim"><form class="card" id="sim"><label>CEP<input required maxlength="8"></label><label>Quantidade<input type="number" min="1" value="1"></label><label>Serviço<select><option>PAC</option><option>SEDEX</option></select></label><button>Simular</button></form><article class="card"><div class="empty">A simulação financeira será liberada somente quando uma tabela de preços estiver vinculada à operação. Nenhuma tarifa é inventada.</div></article></div>`);bindFilters();root.querySelector("#sim").onsubmit=e=>{e.preventDefault();toast("Tabela de preços ainda não configurada.")}}
function lotLabel(s){if(s==="READY_FOR_UNIFIED_LABEL")return["Autorizado","ok"];if(s==="DCE_PREPARED")return["Aguardando autorização","warn"];if(["DCE_RESERVED","DCE_PARTIAL"].includes(s))return["Autorização em andamento","info"];return["Em preparo pela agência","warn"]}
function authorization(){const lots=S.lots.filter(x=>(x.DOCUMENT_MODE||x.documentMode)==="DCE_AUTHORIZED");shell(`<div class="hero"><h1>Autorizar DC-e</h1><p>Autorize somente os lotes preparados pela agência usando o e-CNPJ A1 da própria operação.</p></div><div class="authgrid"><div>${lots.map(x=>{const s=String(x.STATUS||x.status),[l,c]=lotLabel(s);return `<article class="card lot"><div><h3>Lote DC-e #${h(String(x.ID||x.id).slice(0,12))}</h3><span class="pill ${c}">${l}</span></div><section><b>${fmt(x.TOTAL||x.total)}<small>Documentos</small></b><b>${fmt(x.PAC||x.pac)}<small>PAC</small></b><b>${fmt(x.SEDEX||x.sedex)}<small>SEDEX</small></b></section>${s==="DCE_PREPARED"?`<button data-lot="${h(x.ID||x.id)}">Autorizar este lote</button>`:""}</article>`}).join("")||'<article class="card empty">Nenhum lote DC-e preparado.</article>'}</div><aside class="card cert"><h2>e-CNPJ A1</h2><label>Certificado<input id="cert" type="file" accept=".pfx,.p12"></label><label>Senha<input id="pass" type="password"></label><label><input type="radio" name="env" value="2" checked> Homologação</label><label><input type="radio" name="env" value="1"> Produção</label><p>O certificado permanece somente na memória desta sessão.</p></aside></div>`);root.querySelector("#cert")?.addEventListener("change",async e=>{const f=e.target.files[0];if(f){S.certName=f.name;S.cert=await fileToBase64(f)}});root.querySelector("#pass")?.addEventListener("change",e=>S.pass=e.target.value);root.querySelectorAll('[name="env"]').forEach(i=>i.onchange=()=>S.env=i.value);root.querySelectorAll("[data-lot]").forEach(b=>b.onclick=()=>authorize(b.dataset.lot))}
async function authorize(id){S.pass=root.querySelector("#pass")?.value||S.pass;if(!S.cert||!S.pass)return toast("Selecione o A1 e informe a senha.","error");const stop=busy("Autorizando lote...");try{const cert=await api("/api/dce/certificate",{method:"POST",body:JSON.stringify({certificateBase64:S.cert,passphrase:S.pass})}),c=campaign();if(c?.cnpj&&String(cert.cnpj||"").replace(/\D/g,"").slice(0,8)!==String(c.cnpj).replace(/\D/g,"").slice(0,8))throw new Error("O CNPJ-base do certificado não corresponde à operação.");const reserved=await dataAction("productionDce.reserve",{campaignId:S.campaignId,productionBatchId:id,environment:S.env}),docs=reserved.documents||[];for(let i=0;i<docs.length;i+=5){const r=await api("/api/dce/authorize",{method:"POST",body:JSON.stringify({documents:docs.slice(i,i+5),certificateBase64:S.cert,passphrase:S.pass,confirmProduction:S.env==="1"})});await dataAction("batch.saveResults",{batchId:reserved.id,results:r.results})}await dataAction("productionDce.syncResults",{campaignId:S.campaignId,productionBatchId:id});toast("Autorização concluída e devolvida ao lote.","success");await loadData();authorization()}catch(e){toast(e.message,"error")}finally{stop()}}
async function fiscalModal(){root.querySelector(".profile-menu").classList.remove("open");const stop=busy("Abrindo perfil fiscal...");try{S.company=await dataAction("company.get",{});const p=S.company?.profile||{},a=p.address||{},m=root.querySelector(".modal");m.classList.add("open");m.innerHTML=`<section><button id="close">×</button><h2>Perfil fiscal</h2><form id="fiscal"><input name="cnpj" placeholder="CNPJ" value="${h(p.cnpj||campaign()?.cnpj||"")}" required><input name="name" placeholder="Razão social" value="${h(p.name||campaign()?.name||"")}" required><input name="series" placeholder="Série" value="${h(p.series??0)}" required><input name="nextNumber" placeholder="Próximo número" value="${h(S.company?.nextNumber||1)}" required>${["street","number","complement","district","city","uf","zip","cityCode"].map(k=>`<input name="${k}" placeholder="${k}" value="${h(a[k]||"")}" ${k==="complement"?"":"required"}>`).join("")}<label><input name="nonIcmsContributor" type="checkbox" ${p.nonIcmsContributor?"checked":""}> Não contribuinte do ICMS</label><label><input name="operationWithoutInvoice" type="checkbox" ${p.operationWithoutInvoice?"checked":""}> Operação sem nota fiscal</label><button>Salvar</button></form></section>`;m.querySelector("#close").onclick=()=>m.classList.remove("open");m.querySelector("#fiscal").onsubmit=async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget)),profile={cnpj:v.cnpj,name:v.name,series:Number(v.series),nonIcmsContributor:v.nonIcmsContributor==="on",operationWithoutInvoice:v.operationWithoutInvoice==="on",address:{street:v.street,number:v.number,complement:v.complement,district:v.district,city:v.city,uf:String(v.uf).toUpperCase(),zip:String(v.zip).replace(/\D/g,""),cityCode:String(v.cityCode).replace(/\D/g,""),countryCode:"1058",country:"BRASIL"}};await dataAction("company.upsert",{profile,nextNumber:Number(v.nextNumber)});m.classList.remove("open");toast("Perfil fiscal salvo.","success")}}catch(e){toast(e.message,"error")}finally{stop()}}
function render(){S.view==="dashboard"?dashboard():S.view==="simulator"?simulator():authorization()}
async function loadData(){[S.ops,S.lots]=await Promise.all([dataAction("operations.list",{campaignId:S.campaignId}),dataAction("productionDce.list",{campaignId:S.campaignId})])}
async function start(){const stop=busy("Abrindo portal...");try{S.campaigns=await dataAction("campaigns.list",{});if(!S.campaigns.length)throw new Error("Seu usuário ainda não possui uma operação vinculada.");S.campaignId=S.campaigns[0].id;await loadData();render()}catch(e){toast(e.message,"error")}finally{stop()}}
(async()=>{try{S.user=await getUser()}catch{}S.user?await start():loginView()})();
